# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import robotenv_pb2 as robotenv__pb2


class RobotEnvStub(object):
    """RobotEnv service manages robot hardware and provides control interface.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObservationSpec = channel.unary_unary(
                '/robotenv.RobotEnv/GetObservationSpec',
                request_serializer=robotenv__pb2.GetObservationSpecRequest.SerializeToString,
                response_deserializer=robotenv__pb2.ObservationSpec.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/robotenv.RobotEnv/GetConfig',
                request_serializer=robotenv__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=robotenv__pb2.RobotConfig.FromString,
                )
        self.Reset = channel.unary_unary(
                '/robotenv.RobotEnv/Reset',
                request_serializer=robotenv__pb2.ResetRequest.SerializeToString,
                response_deserializer=robotenv__pb2.ResetResponse.FromString,
                )
        self.Step = channel.unary_unary(
                '/robotenv.RobotEnv/Step',
                request_serializer=robotenv__pb2.StepRequest.SerializeToString,
                response_deserializer=robotenv__pb2.StepResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/robotenv.RobotEnv/HealthCheck',
                request_serializer=robotenv__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=robotenv__pb2.HealthCheckResponse.FromString,
                )


class RobotEnvServicer(object):
    """RobotEnv service manages robot hardware and provides control interface.
    """

    def GetObservationSpec(self, request, context):
        """GetObservationSpec returns the schema of observations this robot provides.
        Call this once at startup to understand what fields are available.

        Example: If robot provides joint_positions and cartesian_position,
        control loop knows it can use both for policy input.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """GetConfig returns robot hardware configuration.
        Includes gripper type, frame type, degrees of freedom, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset robot to initial state.
        Supports different reset modes: home, random, target position, or current.

        Returns initial observation after reset completes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Step executes one action and returns the resulting observation.
        This is a blocking call - returns when action is executed and fresh observation is ready.

        Action is provided in the specified action_space (e.g., cartesian_velocity, joint_position).
        Returns robot state observation after executing the action.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck verifies service is running and ready.
        Used for service discovery and readiness probes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObservationSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObservationSpec,
                    request_deserializer=robotenv__pb2.GetObservationSpecRequest.FromString,
                    response_serializer=robotenv__pb2.ObservationSpec.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=robotenv__pb2.GetConfigRequest.FromString,
                    response_serializer=robotenv__pb2.RobotConfig.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=robotenv__pb2.ResetRequest.FromString,
                    response_serializer=robotenv__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=robotenv__pb2.StepRequest.FromString,
                    response_serializer=robotenv__pb2.StepResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=robotenv__pb2.HealthCheckRequest.FromString,
                    response_serializer=robotenv__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotenv.RobotEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotEnv(object):
    """RobotEnv service manages robot hardware and provides control interface.
    """

    @staticmethod
    def GetObservationSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotenv.RobotEnv/GetObservationSpec',
            robotenv__pb2.GetObservationSpecRequest.SerializeToString,
            robotenv__pb2.ObservationSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotenv.RobotEnv/GetConfig',
            robotenv__pb2.GetConfigRequest.SerializeToString,
            robotenv__pb2.RobotConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotenv.RobotEnv/Reset',
            robotenv__pb2.ResetRequest.SerializeToString,
            robotenv__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotenv.RobotEnv/Step',
            robotenv__pb2.StepRequest.SerializeToString,
            robotenv__pb2.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotenv.RobotEnv/HealthCheck',
            robotenv__pb2.HealthCheckRequest.SerializeToString,
            robotenv__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
